// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyB5qR18wnSJhVKAugcHVyIO64Om3VnBVnw",
    authDomain: "bdempleo-2c46c.firebaseapp.com",
    databaseURL:
        "https://bdempleo-2c46c-default-rtdb.europe-west1.firebasedatabase.app",
    projectId: "bdempleo-2c46c",
    storageBucket: "bdempleo-2c46c.firebasestorage.app",
    messagingSenderId: "930180343463",
    appId: "1:930180343463:web:013d925ec3b6129b3add82",
    measurementId: "G-66WY728BB7",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: "AIzaSyB5qR18wnSJhVKAugcHVyIO64Om3VnBVnw",
    authDomain: "bdempleo-2c46c.firebaseapp.com",
    databaseURL:
        "https://bdempleo-2c46c-default-rtdb.europe-west1.firebasedatabase.app",
    projectId: "bdempleo-2c46c",
    storageBucket: "bdempleo-2c46c.firebasestorage.app",
    messagingSenderId: "930180343463",
    appId: "1:930180343463:web:013d925ec3b6129b3add82",
    measurementId: "G-66WY728BB7",
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: "AIzaSyB5qR18wnSJhVKAugcHVyIO64Om3VnBVnw",
    authDomain: "bdempleo-2c46c.firebaseapp.com",
    databaseURL:
        "https://bdempleo-2c46c-default-rtdb.europe-west1.firebasedatabase.app",
    projectId: "bdempleo-2c46c",
    storageBucket: "bdempleo-2c46c.firebasestorage.app",
    messagingSenderId: "930180343463",
    appId: "1:930180343463:web:013d925ec3b6129b3add82",
    measurementId: "G-66WY728BB7",
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: "AIzaSyB5qR18wnSJhVKAugcHVyIO64Om3VnBVnw",
    authDomain: "bdempleo-2c46c.firebaseapp.com",
    databaseURL:
        "https://bdempleo-2c46c-default-rtdb.europe-west1.firebasedatabase.app",
    projectId: "bdempleo-2c46c",
    storageBucket: "bdempleo-2c46c.firebasestorage.app",
    messagingSenderId: "930180343463",
    appId: "1:930180343463:web:013d925ec3b6129b3add82",
    measurementId: "G-66WY728BB7",
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: "AIzaSyB5qR18wnSJhVKAugcHVyIO64Om3VnBVnw",
    authDomain: "bdempleo-2c46c.firebaseapp.com",
    databaseURL:
        "https://bdempleo-2c46c-default-rtdb.europe-west1.firebasedatabase.app",
    projectId: "bdempleo-2c46c",
    storageBucket: "bdempleo-2c46c.firebasestorage.app",
    messagingSenderId: "930180343463",
    appId: "1:930180343463:web:013d925ec3b6129b3add82",
    measurementId: "G-66WY728BB7",
  );
}
