// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdBIl3ee6A7kMa2Oq3cf2_g7b_ZCHFWwc',
    appId: '1:79209380711:web:3ca7c1f99521fb5512cdc2',
    messagingSenderId: '79209380711',
    projectId: 'bolsa-de-empleo-sgema',
    authDomain: 'bolsa-de-empleo-sgema.firebaseapp.com',
    storageBucket: 'bolsa-de-empleo-sgema.firebasestorage.app',
    measurementId: 'G-TM5D983E5W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIjqCWM2XIRwqG_-1H11X2k2f6Q1IolpU',
    appId: '1:79209380711:android:65154aea9fa940ae12cdc2',
    messagingSenderId: '79209380711',
    projectId: 'bolsa-de-empleo-sgema',
    storageBucket: 'bolsa-de-empleo-sgema.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCN4i6cZXwcbVTRGm4AJjLL6X4r4b-wwYE',
    appId: '1:79209380711:ios:0b37d56ddf0765dd12cdc2',
    messagingSenderId: '79209380711',
    projectId: 'bolsa-de-empleo-sgema',
    storageBucket: 'bolsa-de-empleo-sgema.firebasestorage.app',
    iosBundleId: 'com.example.appAlumnos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCN4i6cZXwcbVTRGm4AJjLL6X4r4b-wwYE',
    appId: '1:79209380711:ios:0b37d56ddf0765dd12cdc2',
    messagingSenderId: '79209380711',
    projectId: 'bolsa-de-empleo-sgema',
    storageBucket: 'bolsa-de-empleo-sgema.firebasestorage.app',
    iosBundleId: 'com.example.appAlumnos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdBIl3ee6A7kMa2Oq3cf2_g7b_ZCHFWwc',
    appId: '1:79209380711:web:78db3bdd20a5439a12cdc2',
    messagingSenderId: '79209380711',
    projectId: 'bolsa-de-empleo-sgema',
    authDomain: 'bolsa-de-empleo-sgema.firebaseapp.com',
    storageBucket: 'bolsa-de-empleo-sgema.firebasestorage.app',
    measurementId: 'G-NKYDVZFGRD',
  );
}
